[package]
name = "pgtools"
version = "0.1.1"
edition = "2021"

[dependencies]
log = "0.4"
semver = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["process"] }
url = "2"
